config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  resources :dashboard, only: [:index]
  resources :organizations, only: [:index], path: 'household'
  resources :investment_accounts

  # Defines the root path route ("/")
  # root "posts#index"
  root to: redirect('/dashboard')
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/investment_account.rb
# frozen_string_literal: true

class InvestmentAccount < ApplicationRecord
  belongs_to :organization
  has_many :transactions
  validates :name, presence: true

  scope :active, -> { where(is_deleted: false) }
  scope :deleted, -> { where(is_deleted: true) }

  def total_contributions
    transactions.sum(:amount)
  end
end

app/models/organization.rb
# frozen_string_literal: true

class Organization < ApplicationRecord
  has_many :organization_memberships, dependent: :destroy
  has_many :users, through: :organization_memberships
  has_many :investment_accounts, dependent: :destroy
end

app/models/organization_membership.rb
# frozen_string_literal: true

class OrganizationMembership < ApplicationRecord
  belongs_to :organization
  belongs_to :user

  SUPPORTED_ROLES = %w[
    member
    admin
  ].freeze

  validates :role, inclusion: {
    in: SUPPORTED_ROLES,
    message: '%<value>s is not a valid role'
  }
end

app/models/transaction.rb
# frozen_string_literal: true

class Transaction < ApplicationRecord
  belongs_to :investment_account

  def transaction_type
    if amount >= 0
      'contribution'
    else
      'withdrawal'
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :organization_memberships, dependent: :destroy
  has_many :organizations, through: :organization_memberships

  after_create :create_default_organization, if: :no_organization?

  validate :only_one_organization
  validates :first_name, :last_name, presence: true

  def membership
    organization.organization_memberships.where(user_id: id).first
  end

  def organization
    organizations.first
  end

  def organization_membership
    organization_memberships.first
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def admin?
    membership.role == 'admin'
  end

  private

  def only_one_organization
    return if organizations.count.zero? || (organizations.count == 1)

    errors.add(:organization, 'A user can only belong to one organization')
  end

  def create_default_organization
    default_organization = Organization.create(name: I18n.t('models.organization.fields.name.default'))
    OrganizationMembership.create(user_id: id, organization_id: default_organization.id, role: 'admin')
  end

  def no_organization?
    organizations.empty?
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pundit::Authorization

  before_action :authenticate_user!
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  def index
    @accounts = current_user.organization.investment_accounts.active
  end
end

app/controllers/investment_accounts_controller.rb
# frozen_string_literal: true

class InvestmentAccountsController < ApplicationController
  def index
    @accounts = current_user.organization.investment_accounts.active
  end

  def show
    @investment_account = InvestmentAccount.find(params[:id])
    authorize @investment_account
  rescue Pundit::NotAuthorizedError
    flash[:alert] = t('views.default.flash.not_authorized')
    redirect_to investment_accounts_path
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = t('views.default.flash.not_found')
    redirect_to investment_accounts_path
  end

  def new
    @investment_account = InvestmentAccount.new
  end

  def edit
    @investment_account = InvestmentAccount.find(params[:id])
    authorize @investment_account
  rescue Pundit::NotAuthorizedError
    flash[:alert] = t('views.default.flash.not_authorized')
    redirect_to investment_accounts_path
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = t('views.default.flash.not_found')
    redirect_to investment_accounts_path
  end

  def create
    @investment_account = InvestmentAccount.new(investment_account_params)

    if @investment_account.save
      flash[:notice] = t('views.investment_accounts.create.flash.success', name: @investment_account.name)
      redirect_to investment_accounts_path
    else
      flash.now[:alert] = t('views.investment_accounts.create.flash.failure', name: @investment_account.name)
      render :new
    end
  end

  def update
    investment_account_id = params[:id].to_i
    @investment_account = authorize InvestmentAccount.find_by(id: investment_account_id)
    if @investment_account.update(investment_account_params)
      flash[:notice] = t('views.investment_accounts.update.flash.success', name: @investment_account.name)
      redirect_to @investment_account
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    investment_account_id = params[:id].to_i
    @investment_account = authorize InvestmentAccount.find_by(id: investment_account_id)

    @investment_account.is_deleted = true
    @investment_account.deleted_at = DateTime.now.utc
    if @investment_account.save
      flash[:notice] = t('views.investment_accounts.destroy.flash.success', name: @investment_account.name)
      redirect_to investment_accounts_path
    else
      flash[:alert] = t('views.investment_accounts.destroy.flash.failure', name: @investment_account.name)
      render :show
    end
  rescue Pundit::NotAuthorizedError
    flash[:alert] = t('views.default.flash.not_authorized')
    redirect_to investment_account_path(@investment_account)
  end

  private

  def investment_account_params
    params.require(:investment_account).permit(:name, :description, :contribution_limit, :organization_id)
  end
end

app/controllers/organizations_controller.rb
# frozen_string_literal: true

class OrganizationsController < ApplicationController
  def index
    @organization = current_user.organization
    @members = @organization.users.includes(:organization_memberships)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def user_initials(user: nil)
    first_name = user.first_name
    last_name = user.last_name

    return 'NA' if first_name.empty? && last_name.empty?

    "#{first_name.first}#{last_name.first}"
  end

  def humanize_money(cents)
    Money.from_cents(cents)
  end
end

app/views/dashboard/index.html.erb
<%= render 'layouts/page_container', header: t('views.dashboard.index.header') do %>
  <div>
    <span class="whitespace-nowrap rounded-md border border-brand-500 px-2 py-3 text-2xl font-semibold text-brand-700 cursor-pointer">
      All accounts
      </span>
    <% @accounts.each do |account| %>
      <!-- Solid -->

      <!--    <span class="whitespace-nowrap rounded-full bg-purple-100 px-2.5 py-0.5 text-sm text-purple-700">-->
      <!--    Live-->
      <!--    </span>-->

      <!-- Outlined -->

      <span class="whitespace-nowrap rounded-md border border-brand-500 px-2 py-3 text-2xl font-semibold text-brand-700 cursor-pointer">
        <%= account.name %>
      </span>

    <% end %>
  </div>

<% end %>

app/views/investment_accounts/_account.html.erb
<%= link_to investment_account_path(account) do %>
  <li class="flex justify-between gap-x-6 pb-4">
    <div class="flex min-w-0 gap-x-4">
      <p class="text-white text-xl bg-brand-400 flex items-center justify-center w-14 h-14 rounded">
        <%= account.name.first %>
      </p>
      <div class="min-w-0 flex-auto">
        <p class="text-sm font-semibold leading-6 text-gray-900"><%= account.name %></p>
        <p class="mt-1 truncate text-xs leading-5 text-gray-500"><%= account.description %></p>
      </div>
    </div>
    <div class="hidden shrink-0 sm:flex sm:flex-col sm:items-end">
      <p class="text-sm leading-6 text-gray-900"><%= account.contribution_limit %></p>
    </div>
  </li>
<% end %>

app/views/investment_accounts/_show_header_controls.html.erb
<div class="flex flex-row gap-x-4 px-4 py-6 sm:px-6 lg:px-8">
  <%= link_to t('views.default.actions.edit'), edit_investment_account_path(@investment_account), class: 'button max-w-24 w-auto max-h-10 h-auto ml-auto' %>


  <%= button_to investment_account_path(@investment_account), method: :delete, form: { data: { turbo_confirm: t('views.investment_accounts.show.buttons.confirm_delete') } }, class: 'destroy-button max-w-24 w-auto max-h-10 h-auto ml-auto', 'aria-label': 'Delete' do %>
    <%= t('views.default.actions.delete') %>
  <% end %>
</div>

app/views/investment_accounts/edit.html.erb
<%= render 'layouts/page_header', header: t('views.investment_accounts.edit.header') %>

<div class="max-w-lg">

  <%= form_with model: @investment_account do |f| %>

    <%= f.hidden_field :organization_id, value: current_user.organization.id %>

    <div class="flex flex-col pb-4">
      <%= f.label :name, t('views.investment_accounts.new.fields.name'), class: "label text-xl" %>
      <%= f.text_field :name, class: "text-field text-xl", autofocus: true, required: true %>
      <%= render 'layouts/forms/input_error', model: @investment_account, field: :name %>
    </div>

    <div class="flex flex-col pb-4 max-w-lg">
      <%= f.label :description, t('views.investment_accounts.new.fields.description'), class: "label text-xl" %>
      <%= f.text_field :description, class: "text-field text-xl", autofocus: true %>
      <%= render 'layouts/forms/input_error', model: @investment_account, field: :description %>
    </div>

    <div class="flex flex-col pb-4 max-w-lg">
      <%= f.label :contribution_limit, t('views.investment_accounts.new.fields.contribution_limit'), class: "label text-xl" %>
      <%= f.number_field :contribution_limit, class: "text-field text-xl", autofocus: true %>
      <%= render 'layouts/forms/input_error', model: @investment_account, field: :contribution_limit %>
    </div>

    <div class="flex mt-4">
      <%= f.submit nil, class: "button" %>
    </div>

  <% end %>

</div>

app/views/investment_accounts/index.html.erb
<%= render 'layouts/page_container', header: t('views.investment_accounts.index.header') do %>
  <div class="flex pb-4">
    <%= render 'layouts/page_subheader', subheader: t('views.investment_accounts.index.subheader') %>
    <%= link_to 'New', new_investment_account_path, class: 'button max-w-24 w-auto max-h-10 ml-auto' %>
  </div>

  <ul>
    <% @accounts.each do |account| %>
      <%= render 'account', account: account %>
    <% end %>
  </ul>
<% end %>

app/views/investment_accounts/new.html.erb
<%= render 'layouts/page_header', header: t('views.investment_accounts.new.header') %>

<div class="max-w-lg">

  <%= form_with model: @investment_account do |f| %>

    <%= f.hidden_field :organization_id, value: current_user.organization.id %>

    <div class="flex flex-col pb-4">
      <%= f.label :name, t('views.investment_accounts.new.fields.name'), class: "label text-xl" %>
      <%= f.text_field :name, class: "text-field text-xl", autofocus: true, required: true %>
      <%= render 'layouts/forms/input_error', model: @investment_account, field: :name %>
    </div>

    <div class="flex flex-col pb-4 max-w-lg">
      <%= f.label :description, t('views.investment_accounts.new.fields.description'), class: "label text-xl" %>
      <%= f.text_field :description, class: "text-field text-xl", autofocus: true %>
      <%= render 'layouts/forms/input_error', model: @investment_account, field: :description %>
    </div>

    <div class="flex flex-col pb-4 max-w-lg">
      <%= f.label :contribution_limit, t('views.investment_accounts.new.fields.contribution_limit'), class: "label text-xl" %>
      <%= f.number_field :contribution_limit, class: "text-field text-xl", autofocus: true %>
      <%= render 'layouts/forms/input_error', model: @investment_account, field: :contribution_limit %>
    </div>

    <div class="flex mt-4">
      <%= f.submit nil, class: "button" %>
    </div>

  <% end %>

</div>

app/views/investment_accounts/show.html.erb
<%= render 'layouts/page_container', header: t('views.investment_accounts.show.header'), header_controls: render('show_header_controls') do %>

  <div class="grid grid-cols-12 gap-4 w-100 h-full">
    <div class="col-span-8 border rounded-lg bg-white p-4">
      <%= render 'layouts/page_subheader', subheader: t('views.investment_accounts.show.performance.subheader') %>
    </div>
    <div class="col-span-4">
      <div class="grid grid-rows-12 gap-4 w-100 h-full">
        <div class="row-span-6 border rounded-lg bg-white p-4">
          <%= render 'layouts/page_subheader', subheader: t('views.investment_accounts.show.details.subheader') %>
          <div class="flex flex-col pb-4">
            <div class="label text-xl">
              <%= t('views.investment_accounts.new.fields.name') %>
            </div>
            <div class="text-xl">
              <%= @investment_account.name %>
            </div>
          </div>

          <div class="flex flex-col pb-4">
            <div class="label text-xl">
              <%= t('views.investment_accounts.new.fields.description') %>
            </div>
            <div class="text-xl">
              <%= @investment_account.description %>
            </div>
          </div>

          <div class="flex flex-col pb-4">
            <div class="label text-xl">
              <%= t('views.investment_accounts.new.fields.contribution_limit') %>
            </div>
            <div class="text-xl">
              $<%= humanize_money(@investment_account.contribution_limit) %>
            </div>
          </div>

          <div class="flex flex-col pb-4">
            <div class="label text-xl">
              <%= t('views.investment_accounts.new.fields.contributions') %>
            </div>
            <div class="text-xl">
              $<%= humanize_money(@investment_account.total_contributions) %>
            </div>
          </div>

        </div>

        <div class="row-span-6 border rounded-lg bg-white p-4">
          <%= render 'layouts/page_subheader', subheader: t('views.investment_accounts.show.activity.subheader') %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_alerts.html.erb
<% if notice %>
  <div class="alert info-alert" role="alert">
    <div class="flex">
      <div>
        <p><%= notice %></p>
      </div>
      <span class="ml-auto" role="button" aria-label="Close alert">
    <svg class="<%= "fill-current h-6 w-6 text-blue-500" %>" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
  </span>
    </div>
  </div>
<% end %>
<% if alert %>
  <div class="alert danger-alert" role="alert">
    <div class="flex">
      <div>
        <p><%= alert %></p>
      </div>
      <span class="ml-auto" role="button" aria-label="Close alert">
    <svg class="<%= "fill-current h-6 w-6 text-red-500" %>" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
  </span>
    </div>
  </div>
<% end %>

app/views/layouts/_app.html.erb
<div class="min-h-full">
  <%= render 'layouts/nav' %>
  <%= yield %>
</div>

app/views/layouts/_nav.html.erb
<nav class="bg-brand-800">
  <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
    <div class="flex h-16 items-center justify-between">
      <div class="flex items-center">
        <div class="flex-shrink-0">
          <!--            <img class="h-8 w-8" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=500" alt="Your Company">-->
          <div class="h-8 w-8 text-3xl">💰</div>
        </div>
        <div class="hidden md:block">
          <div class="ml-10 flex items-baseline space-x-4">
            <%= link_to dashboard_index_path, class: "rounded-md bg-brand-900 px-3 py-2 text-sm font-medium text-white" do %>
              <%= t('views.nav.links.dashboard') %>
            <% end %>
            <%= link_to investment_accounts_path, class: "rounded-md px-3 py-2 text-sm font-medium text-brand-300 hover:bg-brand-700 hover:text-white" do %>
              <%= t('views.nav.links.investment_accounts') %>
            <% end %>
            <%= link_to organizations_path, class: "rounded-md px-3 py-2 text-sm font-medium text-brand-300 hover:bg-brand-700 hover:text-white" do %>
              <%= t('views.nav.links.household') %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="hidden md:block">
        <div class="ml-4 flex items-center md:ml-6">
          <button type="button" class="relative rounded-full bg-brand-800 p-1 text-brand-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-brand-800">
            <span class="absolute -inset-1.5"></span>
            <span class="sr-only">View notifications</span>
            <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0" />
            </svg>
          </button>

          <!-- Profile dropdown -->
          <div class="relative ml-3">
            <div>
              <button type="button" class="relative flex max-w-xs items-center rounded-full bg-brand-800 text-sm focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-brand-800" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
                <span class="absolute -inset-1.5"></span>
                <span class="sr-only">Open user menu</span>
                <img class="h-8 w-8 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
              </button>
            </div>

            <!--
              Dropdown menu, show/hide based on menu state.

              Entering: "transition ease-out duration-100"
                From: "transform opacity-0 scale-95"
                To: "transform opacity-100 scale-100"
              Leaving: "transition ease-in duration-75"
                From: "transform opacity-100 scale-100"
                To: "transform opacity-0 scale-95"
            -->
            <div class="hidden absolute right-0 z-10 mt-2 w-48 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1">
              <!-- Active: "bg-brand-100", Not Active: "" -->
              <a href="#" class="block px-4 py-2 text-sm text-brand-700" role="menuitem" tabindex="-1" id="user-menu-item-0">Your Profile</a>
              <a href="#" class="block px-4 py-2 text-sm text-brand-700" role="menuitem" tabindex="-1" id="user-menu-item-1">Settings</a>
              <a href="#" class="block px-4 py-2 text-sm text-brand-700" role="menuitem" tabindex="-1" id="user-menu-item-2">Sign out</a>
            </div>
          </div>
        </div>
      </div>
      <div class="-mr-2 flex md:hidden">
        <!-- Mobile menu button -->
        <button type="button" class="relative inline-flex items-center justify-center rounded-md bg-brand-800 p-2 text-brand-400 hover:bg-brand-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-brand-800" aria-controls="mobile-menu" aria-expanded="false">
          <span class="absolute -inset-0.5"></span>
          <span class="sr-only">Open main menu</span>
          <!-- Menu open: "hidden", Menu closed: "block" -->
          <svg class="block h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
          <!-- Menu open: "block", Menu closed: "hidden" -->
          <svg class="hidden h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
    </div>
  </div>

  <!-- Mobile menu, show/hide based on menu state. -->
  <div class="md:hidden" id="mobile-menu">
    <div class="space-y-1 px-2 pb-3 pt-2 sm:px-3">
      <%= link_to dashboard_index_path, class: "block rounded-md bg-brand-900 px-3 py-2 text-base font-medium text-white" do %>
        <%= t('views.nav.links.dashboard') %>
      <% end %>
      <%= link_to investment_accounts_path, class: "block rounded-md px-3 py-2 text-base font-medium text-brand-300 hover:bg-brand-700 hover:text-white" do %>
        <%= t('views.nav.links.investment_accounts') %>
      <% end %>
      <%= link_to organizations_path, class: "block rounded-md px-3 py-2 text-base font-medium text-brand-300 hover:bg-brand-700 hover:text-white" do %>
        <%= t('views.nav.links.household') %>
      <% end %>
    </div>
    <div class="border-t border-brand-700 pb-3 pt-4">
      <div class="flex items-center px-5">
        <div class="flex-shrink-0">
          <img class="h-10 w-10 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
        </div>
        <div class="ml-3">
          <div class="text-base font-medium leading-none text-white">Tom Cook</div>
          <div class="text-sm font-medium leading-none text-brand-400">tom@example.com</div>
        </div>
        <button type="button" class="relative ml-auto flex-shrink-0 rounded-full bg-brand-800 p-1 text-brand-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-brand-800">
          <span class="absolute -inset-1.5"></span>
          <span class="sr-only">View notifications</span>
          <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0" />
          </svg>
        </button>
      </div>
      <div class="hidden mt-3 space-y-1 px-2">
        <a href="#" class="block rounded-md px-3 py-2 text-base font-medium text-brand-400 hover:bg-brand-700 hover:text-white">Your Profile</a>
        <a href="#" class="block rounded-md px-3 py-2 text-base font-medium text-brand-400 hover:bg-brand-700 hover:text-white">Settings</a>
        <a href="#" class="block rounded-md px-3 py-2 text-base font-medium text-brand-400 hover:bg-brand-700 hover:text-white">Sign out</a>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_page_container.html.erb
<% header_controls = header_controls || nil %>

<%= render 'layouts/page_header', header: header, header_controls: header_controls %>
<main>
  <div class="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
    <%= yield %>
  </div>
</main>

app/views/layouts/_page_header.html.erb
<% header_controls = header_controls || nil %>

<header class="border border-b-1 border-t-0 border-r-0 border-l-0">
  <div class="flex flex-row items-center">
    <div class="max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
      <h1 class="text-3xl font-bold tracking-tight text-brand-900"><%= header %></h1>
    </div>
    <% if header_controls %>
      <div class="ml-auto">
        <%= header_controls %>
      </div>
    <% end %>
  </div>
</header>

app/views/layouts/_page_subheader.html.erb
<div class="text-2xl font-semibold pb-4">
  <%= subheader %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full bg-white">
  <head>
    <title>Piggy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= vite_client_tag %>
    <%= vite_stylesheet_tag 'application', data: { "turbo-track": "reload" } %>
    <%= vite_javascript_tag 'application' %>
  </head>

  <body class="h-full">
    <%= render 'layouts/alerts' %>
    <% if current_user %>
      <%= render 'layouts/app' %>
    <% else %>
      <%= yield %>
    <% end %>
  </body>
</html>

app/views/layouts/forms/_input_error.html.erb
<% if model.errors[field.to_sym].empty? == false %>
  <div class="flex flex-col">
    <% model.errors.full_messages_for(field.to_sym).each do |error| %>
      <span class="text-sm text-red-600 mt-2"><%= error %></span>
    <% end %>
  </div>
<% end %>

app/views/organizations/_member.html.erb
<li class="flex justify-between gap-x-6 pb-4">
  <div class="flex min-w-0 gap-x-4">
    <p class="text-white text-xl bg-brand-400 flex items-center justify-center w-14 h-14 rounded">
      <%= user_initials(user: member) %>
    </p>
    <div class="min-w-0 flex-auto">
      <p class="text-sm font-semibold leading-6 text-gray-900"><%= member.full_name %></p>
      <p class="mt-1 truncate text-xs leading-5 text-gray-500"><%= member.email %></p>
    </div>
  </div>
  <div class="hidden shrink-0 sm:flex sm:flex-col sm:items-end">
    <p class="text-sm leading-6 text-gray-900"><%=member.membership.role.capitalize %></p>
  </div>
</li>

app/views/organizations/index.html.erb
<%= render 'layouts/page_container', header: @organization.name do %>
  <ul>
    <% @members.each do |member| %>
      <%= render 'organizations/member', member: member %>
    <% end %>
  </ul>
<% end %>

app/views/organizations/show.html.erb
<%= @organization.name %>